spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testDB?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: "czd888"
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  main:
    allow-circular-references: true
server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/other/*.xml
#  mapper-locations: classpath:mapper/*mapper.xml
  type-aliases-package: com.family_financial_system.bean
  configuration:
    map-underscore-to-camel-case: true
